### ISSUE TITLE
missing data in -dev

### ISSUE THREAD

**Issue by willkg** [mozilla-services/buildhub#177]
I'm trying to compare ftpscraper output to buildhub output and there's a lot of missing data.

For example, there's no 52.0.1esr or 52.0.2esr for en-US in buildhub.

It also looks like there's no data after 2017-06-20.

What data does the -dev environment have? Are there better environments to use?

**Comment by leplatrem** [comment]
We improved greatly the completeness of the dev database now that we use S3 inventories.

However, we're not at a stage where updates are live yet (#51)

We'll spend sometime organizing the remaining work to be done in this project, so that it's easier to follow the current status and progress

I apologize for the impact on your work :(

**Comment by willkg** [comment]
This is probably fixed by now so I'm going to close it out. I can always open up a new bug later on with up-to-date details.
