### ISSUE TITLE
Difference between win64 and win64-sha1 ?

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/buildhub#194]
See https://archive.mozilla.org/pub/firefox/releases/45.3.0esr/

**Comment by mozbhearsum** [comment]
@nthomas-mozilla or @rail - do you have any memories on this? I couldn't find anything on https://github.com/mozilla/releasewarrior/blob/master/releases/ARCHIVE/firefox-esr-45.3.0esr.md.

**Comment by nthomas-mozilla** [comment]
I think this was/is the "SHA2 certs for authenticode signing aren't supported on Windows XP and Vista" issue, where requests from those OS are given SHA1-signed installers. IIRC there is some magic in bouncer to make this happen behind the scenes, which has caused no end of confusion. 

I checked in bouncer and there are quite a lot of products with -sha1 suffix, like Firefox-45.4.0esr-sha1. The 45 ESR products appear to point to non-existent paths, because there's no firefox/releases/45.5.0esr/win32-sha1, but there are products and dirs like
 https://archive.mozilla.org/pub/firefox/releases/50.0b11/win32-sha1/
 https://archive.mozilla.org/pub/firefox/releases/49.0.2/win32-sha1/
 https://archive.mozilla.org/pub/firefox/releases/52.1.2esr/win32-sha1/
which appear to be hooked up correctly, even in the 52.3.0esr candidates directory. See also https://bugzilla.mozilla.org/show_bug.cgi?id=1379422

**Comment by leplatrem** [comment]
Thanks a lot for these precious clarifications!

We'll keep it the way it is now on our side, ie. with `platform` field values `win32-sha1` and `win64-sha1`
