### ISSUE TITLE
webui is missing links to repo, issue tracker, and docs

### ISSUE THREAD

**Issue by willkg** [mozilla-services/buildhub#319]
The webui is missing some key bits which would make it easier for other people to collaborate. When looking at the webui, there's no indication of any of the following:

1. Where I can see the code.
2. Where I can file an issue.
3. How to file issues about data problems vs. code problems. Is it the same process? Is there anything that helps you triage/debug/work on things more effectively?
4. Copyright/license information for the data collected. I'm guessing it's public domain, but I have no idea.
5. What I can do with the data.
6. Link to documentation for the webui and the API.

I think the best thing to do is add a footer or a header with a link to the GitHub repository with "Source code", a link to the issue tracker "File an issue here", and a link to the readthedocs docs with "Documentation".

**Comment by leplatrem** [comment]
Thanks for this feedback, indeed that's easy to fix and I agree that it'd have many benefits

**Comment by peterbe** [comment]
This is the kind of questions the `/contribute.json` can answer. But a footer is also a good idea. 
One curious thing is, since buildhub is only available as a "sub directory" of `mozilla-services.github.com` it's not obvious what the URL ought to be. But I guess the only logical URL would be `https://mozilla-services.github.io/buildhub/contribute.json`

**Comment by willkg** [comment]
`contribute.json` is really for machines--not humans. Adding one is great, but doesn't solve my problem. I'm asking for links in a header or footer or menu or something that explain the site, point to docs, point to support, docs on how to raise issues, etc.
