### ISSUE TITLE
Capture and Service Socorros Requirements

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/buildhub#37]
Last month (Apr 24) I talked to @willkg about Socorro's (Crashstats) usage of build info. Socorro currently has an [ftpscraper.py](https://github.com/mozilla/socorro/blob/master/socorro/cron/jobs/ftpscraper.py) that indexes archive.mozilla.org. This populates a [database table](https://gist.github.com/mostlygeek/132fe3a2c2c127ec39c8d4ed667118e0) that's used by various tools for lookup. 

BuildHub should be able to replace their scraper and their custom database table.

**Comment by willkg** [comment]
I was looking at the BuildHub demo yesterday in relation to Socorro's `product_versions` table and @peterbe and I talked about both a bit.

I'm pretty confident we can definitely drop ftpscraper for a script that pulls the data from the BuildHub API. I'm less sure about whether we can drop the Socorro `product_versions` table.

One thing that's exciting is that we're removing tons of code, so it's entirely possible that today we need the table, but at some future date that's not too far off, we won't.

Is the BuildHub API "finalized" enough that we could take a stab at replacing ftpscraper?

**Comment by mostlygeek** [comment]
A Kinto server (we maintain that project too) powers BuildHub. So the [Kinto API](http://docs.kinto-storage.org/en/stable/api/1.x/index.html#full-reference) is the current API. We are open to making changes here to address needs of users.

**Comment by willkg** [comment]
Ok. So you're saying the API *is* finalized enough that we should take a stab at replacing ftpscraper now and that the API is the same as the Kinto API. Is that right?

Is the demo server I saw at https://mozilla-services.github.io/buildhub/# the right API endpoint to use?

**Comment by mostlygeek** [comment]
Sure give it a try. :) Click on the docs link on the UI at: https://mozilla-services.github.io/buildhub/. It should have some snippets to help you start hacking.

**Comment by willkg** [comment]
Oh neato! The Docs link didn't work for me when I checked earlier. Will peruse that. Thank you!

**Comment by Natim** [comment]
It works from here.

Basically, what you need to know is that the collection stand there:

https://kinto-ota.dev.mozaws.net/v1/buckets/build-hub/collections/archives/records?_limit=25

We currently have more than 100k records there so using _limit is greatly recommanded :)

**Comment by willkg** [comment]
I wrote up a bug to rewrite ftpscraper using BuildHub:

https://bugzilla.mozilla.org/show_bug.cgi?id=1366301

Feel free to comment in it if I got anything wrong.

I'm going to try to take a stab at this over the next week time-willing.

**Comment by willkg** [comment]
@Natim @mostlygeek: It looks like there are two collections: "archives" and "builds". What's the difference?

**Comment by Natim** [comment]
`builds` is a collection that we used for few experiments around pulse but you should only rely on the `archives` one

**Comment by willkg** [comment]
That's not obvious especially given that the only documentation I got was "go explore the dataset using the Kinto API". My intuition for naming tells me that "builds" is where the build data would be and "archives" is old data that isn't useful for some reason.

Can you let me know when the data on -dev is cleaned up and representative of what -prod will look like without experiment or junk data? Either that or provide me with a schema for that Kinto server so that I don't have to explore the dataset on my own in the dark?

**Comment by Natim** [comment]
> Can you let me know when the data on -dev is cleaned up and representative of what -prod will look like without experiment or junk data? Either that or provide me with a schema for that Kinto server so that I don't have to explore the dataset on my own in the dark?

Yes, creating a schema is our next step :) I will get back to you asap with a schema.
For now the documentation we have is here: https://mozilla-services.github.io/buildhub/#/docs

While browsing the archives collection did you see any information missing that you would like to see in the schema?

**Comment by willkg** [comment]
Yeah... @mostlygeek mentioned those docs in https://github.com/mozilla-services/buildhub/issues/37#issuecomment-301921413 . It consists of a few recipe examples, but doesn't cover my use cases and doesn't talk about the state of things.

For example, this statement at the top of the docs would have helped a lot:

> Use the "build-hub" bucket and the "builds" collection.

Also, maybe:

> Current status: We're still experimenting with extracting this data, so you might see junk data in the data set. We update the data every xyz. If you see data problems, please report them xyz.

I didn't spend a lot of time browsing the archives collection because I assumed (apparently incorrectly) that it wasn't what I should be looking at.

However, when puttering around exploring the dataset, I did pull some data from it:

https://github.com/willkg/socorro/commit/3ee22b23f8204fe5afd431b2afe15ecea7fec6cb#diff-f17c1bdf552603de8334e105a3ed26f7R22

Based on that, it looks like it's got similar problems that I had with the archives data:

* `target.channel` is null
* `build.type` is "opt" and I'm not sure what that means
* `target.version` doesn't look like a version -- ex: `05-05-00-40-04-comm-aurora-l10n/thunderbird-54.0a2`

Maybe I just happened to pick a build that's junk data?

Hope that helps!

**Comment by Natim** [comment]
> Use the "build-hub" bucket and the "archives" collection.

Archives is the correct collection.

We will the issue you are talking about and I will tell you went we have updated the data so that you can verify that everything is back working for you.

Thank you for your feedback.

**Comment by willkg** [comment]
Updating this, "releases" is the new correct collection.

**Comment by leplatrem** [comment]
I believe the current matches the initial exceptations (completeless, live update). Let's open new issues if specific problems/limitations are detected.
