### ISSUE TITLE
Integrate Datadog and our Lambda function

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/buildhub#433]
According to the documentation it should be possible:
https://docs.datadoghq.com/integrations/amazon_lambda/

When I go to https://app.datadoghq.com/account/settings#integrations/amazon_lambda I *think* what that page is trying to say is that it's enabled. 
<img width="1294" alt="screen shot 2018-04-27 at 12 26 38 pm" src="https://user-images.githubusercontent.com/26739/39373668-5211192a-4a16-11e8-8d63-46d754291f51.png">

This issue is two things:

1. Enable to check that Datadog AWS Lambda integration is enable for the Buildhub context. 
2. Do these `stdout` writes (using our current metrics infra) so that the relevant metrics can be sucked up by the Datadog/Cloudwatch/Lambda integration.

**Comment by peterbe** [comment]
[pigeon does it with a simple print](https://github.com/mozilla-services/socorro-pigeon/blob/master/pigeon.py#L156)

**Comment by peterbe** [comment]
Even better, markus already has a backend for this!
https://github.com/willkg/markus/blob/master/markus/backends/cloudwatch.py

**Comment by bqbn** [comment]
I'm closing this because, correct me if wrong, we now have the lambda metrics in Datadog for -stage, which means once the latest version (v1.3.2 as of this comment) is released to -prod, we should be able to see the same metrics in Datadog for -prod as well.

We can re-open this issue if, when the latest version is released, and we still don't have lambda metrics in Datadog for -prod.
