### ISSUE TITLE
Which arch for Android ARM?

### ISSUE THREAD

**Issue by Natim** [mozilla-services/buildhub#44]
It seems that `scrape_archives` is using android-arm as the platform.

However is there two platform for android? `android-api-9` and `android-api-15`? Can we have the same release compatible with both?

Since the platform is used in the ID of the record, we need to make sure that `android-api-9` releases won't be overridden by `android-api-15` ones and vice et versa.

**Comment by glasserc** [comment]
From https://developer.android.com/guide/topics/manifest/uses-sdk-element.html#ApiLevels, it seems like API levels are backwards compatible, but not forwards compatible. In other words, a device capable of handling `android-api-15` is *generally* capable of handling applications built using `android-api-9`, but not the other way around.

Our release formats seem to have evolved quite a bit. [10](https://archive.mozilla.org/pub/mobile/releases/10.0/android/en-US/) is just released as a single `android-arm` package. Starting in [17](https://archive.mozilla.org/pub/mobile/releases/17.0/) we see `android-armv6` and `android`. Starting in [26](https://archive.mozilla.org/pub/mobile/releases/26.0/) there's `android-armv6`, `android-x86`, and `android`. In [32](https://archive.mozilla.org/pub/mobile/releases/32.0/android/en-US/) we drop back down to `android` and `android-x86`, and in [37](https://archive.mozilla.org/pub/mobile/releases/37.0/) we move to `android-api-9`, `android-api-11`, and `android-x86`. In [46](https://archive.mozilla.org/pub/mobile/releases/46.0/) we switch to `android-api-9`, `android-api-15`, and `android-x86`. In [48](https://archive.mozilla.org/pub/mobile/releases/48.0/) we drop `android-api-9`, leaving just `android-api-15` and `android-x86`, which appears to remain true up to the present.

I think we could legitimately consider processor architecture as well as Android API as part of the ID. We could imagine getting different crashes on `android-x86` (which I think is mainly emulators?) vs. `android-api-15` due to e.g. byte alignment constraints or something. In the same way, we could imagine Fennec developers offering different feature sets on `android-api-15` and `android-api-41` due to the presence or absence of special APIs.

**Comment by glasserc** [comment]
I asked about this in `#mobile` and I got a response from `nalexander`, who told me that we'll "want OS + platform, so {Android} x {ARM, x86, aarch64}", with the additional proviso that "Android generally supports very fine-grained package splits: SDK, device density, screen size, language, processor architecture, etc.  We're just not set up to do that." As a first draft, using Android API version as "{Android}" would be good. I guess there's no point in splitting up platform any more than that until we have a use case for it.

**Comment by leplatrem** [comment]
I'm closing this in favor of #184
