### ISSUE TITLE
New architecture / design for buildhub?

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/buildhub#48]
In the Wednesday meeting @magopian mentioned a new structure/design for the WebUI. Can we document the design / decisions for it on GH?

**Comment by magopian** [comment]
Now that #40 has landed, we have the structure in place to link to any build and any "filtered page". Now we need to address the "how do we deal with the massive amount of data", and for that we have #63 to implement pagination.

This in itself should be sufficient to navigate through all the data.

However, what we discussed was that it might be interesting and more ergonomic to change the way the UI displays the list of filters (a big list on the right), to be more like a "catalog" with categories.

Instead of displaying a big list of the latest 100 builds, and then dynamically filter through it, we could instead present the user with a few filters to select:
- product
- channel
- platform
- version
- locale

The user could then choose one (or many) of those, and start filtering from there. A first request would then be sent to Kinto, to retrieve the (paginated) list of builds that match.

This has a few pros and cons:

pros
====

- No useless list/request at the very beginning, no displaying of useless information on start
- less requests to kinto

cons
====

- the list of filters values will have to be "hardcoded", instead of being computed from the current list (narrowing the list down was updating the filter values, keeping only the relevant ones). It'll thus be possible (and very easy) to select filter values that lead to an empty list
- work will be needed to see how to update this list of filter values (if we have a new locale for example)

Those cons may be partially addressable by using elasticsearch to do the faceting, and using that. We still have to think about the "it's easy to use a combination of filters that gives no result, without any help in this regard": do we have a solution? Do we care?

**Comment by n1k0** [comment]
> Now we need to address the "how do we deal with the massive amount of data"

At our standup today, we mentioned that we don't really expect the database to exceed 80k records. **If true**, this kinda makes overkill using smthg like ES. If **not true**, then you can stop reading the content of this comment. 

We discussed several alternative strategies, like doing everything in memory again (as we did when we started the project), or writing a dedicated kinto plugin to help clients retrieving data more easily. 

The only pain point with the kinto plugin approach is if we want real, actual faceted search, aka updating the list of filters computed against the new results, so you can incrementally refine your search against remaining criterias available on the server.

If we do really want faceted search, only ES and the in-memory approaches are likely to work without much hassle. If our tight schedule (end of June) comes into play, in-memory largely wins I believe (but I may be wrong here, the thing is we won't know for sure until we actively work on this, which I'm planning to do tomorrow anyway).

So the actual question is, do we actually *need* faceted search for our SFO demo? If so, we're gonna need either working hard with consuming ES stuff from Elm (slightly high risk of failure), or move back to in-memory filtering (lower risk of failure).

I may update this thread with the result of my work on ES stuff tomorrow.

**Comment by n1k0** [comment]
Also, if the answer to the *do we want real faceted search?* question is *no, not refining filter select boxes is not needed for our SFO demo*, we can probably safely close this issue as #101, #104 and  #105 addressed all the points, and move to improving the UX and styling.

**Comment by mostlygeek** [comment]
We don't want to load 80K (or more) records into memory and filter it.  I recall somebody saying the initial pull is about 25MB of data and it takes more than 10 seconds (or more) parse? 

@n1k0 Can you define what you mean by faceted search? What is it supposed to do? 

I see that #40 and #63 has landed. Does https://mozilla-services.github.io/buildhub have that code? I only see 10 records and no pages.

**Comment by n1k0** [comment]
> I recall somebody saying the initial pull is about 25MB of data and it takes more than 10 seconds (or more) parse?

If true, that's probably not the best option indeed.

> Can you define what you mean by faceted search?

#### Faceted search

1. I pick "firefox" as a product
2. The *version* filter select box only contains firefox versions

#### Current situation

1. I pick "firefox" as a product
2. Thunderbird versions are still listed in the version filter select box

**Comment by magopian** [comment]
> I see that #40 and #63 has landed. Does https://mozilla-services.github.io/buildhub have that code? I only see 10 records and no pages.

There's the information on how many builds are displayed on the current page (10 by default, until you ask for some more), and the total number of builds. See the following screenshot (top of the page), here 10 displayed for 36452 total):

![screenshot from 2017-06-06 09-20-19](https://cloud.githubusercontent.com/assets/167767/26818071/9b2232ac-4a99-11e7-958d-e015788eb648.png)

At the bottom of the page, if there are any more builds to load, there's a button displaying how many more you can load at once, and the total number of builds left. See the following screenshot (bottom of the page), here "Load 10 more (36442 left)":

![screenshot from 2017-06-06 09-20-35](https://cloud.githubusercontent.com/assets/167767/26818141/d571d3ea-4a99-11e7-90d5-d49442bcf4b8.png)

**Comment by n1k0** [comment]
Yeah, @Natim mentioned 80k as a hard limit yesterday at the standup, that's why I used this figure.

**Comment by n1k0** [comment]
If 10 seconds parsing (or maybe just 5) is true, that makes the app acting like a desktop client instead of a Web one; like if you're sent a URL to see one build details and to have to fetch the whole database and wait that long to have a single record eventually displayed, it's not gonna create a great UX.

Sure we could cache the records into indexedDB or something, but we'd still have to sync it, so that would be kinto.js and friends, and we're speaking Elm here, and the demo is in 3 weeks.

**Comment by mostlygeek** [comment]
I created a bug (#119) for the records not showing up. It appears to only affect FF Nightly. Other browsers appear to work.
