### ISSUE TITLE
Realtime updates of buildhub

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/buildhub#51]
S3 has the ability to post events when objects are uploaded and deleted. Since archive.mozilla.org is an S3 bucket, whenever a new build is uploaded we can be notified and buildhub updated in real time. 

For the flow: 

`upload -> s3 -> SNS -> SQS <- buildhub daemon -> buildhub kinto` 

or

`upload -> s3 -> lambda -> buildub kinto` 

What do you guys think?

**Comment by Natim** [comment]
This could be a great alternative to #50.
Using the archive as a source of truth seems like a good idea.
Also having the archive upload monitored would make our database up-to-date as soon as new updates are available.

**Comment by leplatrem** [comment]
The main problem for this approach is that we'll receive individual events for single files.
For example, this is problematic because we obtain the metadata from json files whereas we are interested in the published archives (.dmg, .tar.gz, etc.)

Using the queue + daemon could help for that but I find it slightly overkill. 

I'll have a look at the specific TC events on Pulse that Ben pointed out, and see what comes out.

**Comment by mostlygeek** [comment]
How about this: 

1. s3 event comes in 
2. event handler (lambda?) will confirm requirements: (json, archives, locales, etc)
3. if requirements all met, process record into BuildHub

This way the event handler can be stateless. It will only move forward once all requirements are met, otherwise it will abort. Presumably at some point a file will be added, all the requirements will be met and it will continue. 

We might have race conditions but I assume kinto has guards against that.

**Comment by leplatrem** [comment]
Yes, why not.

But there is one subtlety: the same metadata info are shared for several locales (and repacks like EME).

So if localized archive comes after the JSON, all fine. However, if the JSON comes after, we'll have to potentially scan a lot of folders to find all related published archives.
