### ISSUE TITLE
Add a version_sort field so that we can sort releases by version

### ISSUE THREAD

**Issue by Natim** [mozilla-services/buildhub#53]

**Comment by glasserc** [comment]
I'm not crazy about exposing this as part of the data model. It's really a field that is derived automatically from the version number. I think adding it as part of the data model is an acceptable compromise, but I'd be happier if we had a Kinto plugin that added it on every save and removed it when serving records.

**Comment by n1k0** [comment]
An important pro for having a dedicated field allowing to order records from the server side is pagination; if you want to paginate filters (eg. distinct values for versions), you actually need to do this server side, otherwise clients need to retrieve the whole list and store it in memory just to render the first 10 items, then the next ten others, etc.

Another alternative would be to store the version as an object instead of a string, eg. {major: 52, minor: 0, suffix: "b4"} instead of `52.0b4`, so that:

- we could *at least* easily sort by major versions
- we could easily expose filters for major, then minor, then suffixes

Thoughts?

**Comment by mostlygeek** [comment]
Having the version list numerically sorted in the UI is required. 

I did some quick searching and there doesn't seem to be a great / idiomatic server side solution for sorting semantic versions and ES. My vote is to punt it to the future. :)

**Comment by Natim** [comment]
What does `punt it` means there?

**Comment by mostlygeek** [comment]
Means do it in the future (maybe).

**Comment by leplatrem** [comment]
Is this is relevant ?

**Comment by Natim** [comment]
@magopian I think you guys figured it out front-end wise, is that correct?
